name: GitHub Actions on Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  call-review-bot-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR changed files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "$PR_NUMBER"
          OWNER=${{ github.repository_owner }}
          echo "$OWNER"
          REPO=${{ github.event.repository.name }}
          echo "$REPO"
          echo "The head SHA of the pull request is: ${{ github.event.pull_request.head.sha }}"
          API_URL="https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/files"
          echo "$API_URL"
          # Fetch the list of changed files using the GitHub API
          # The 'jq' command is used to parse the JSON response
          #CHANGED_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${API_URL}" | jq -r '.[] | .filename + " " + .status + " " + .patch')
          JSON_PAYLOAD=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${API_URL}")
           #echo "::set-output name=changed_files::${CHANGED_FILES}"
          API_URL="https://pitaeva-deploy-code-review-bot.hf.space/reviewcomments" # Replace with your API endpoint
          REQUEST_BODY="{ \"changes\": $JSON_PAYLOAD, \"commit_id\" : \"${{ github.event.pull_request.head.sha }}\", \"owner\" : \"${{ github.repository_owner }}\", \"repo\" : \"${{ github.event.repository.name }}\", \"pull_request_number\" : ${{ github.event.pull_request.number }} }"
          echo "Request body:"
          echo "$REQUEST_BODY"
          RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d "${REQUEST_BODY}" "${API_URL}")
          echo "API Response:"
          echo "$RESPONSE"
          
