name: GitHub Actions on Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  call-review-bot-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR changed files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "$PR_NUMBER"
          OWNER=${{ github.repository_owner }}
          echo "$OWNER"
          REPO=${{ github.event.repository.name }}
          echo "$REPO"
          API_URL="https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/files"
          echo "$API_URL"
          # Fetch the list of changed files using the GitHub API
          # The 'jq' command is used to parse the JSON response
           #CHANGED_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${API_URL}" | jq -r '.[] | .filename + " " + .status + " " + .patch')
           JSON_PAYLOAD=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${API_URL}")
           echo "JSON payload:"
           echo "JSON_PAYLOAD=$JSON_PAYLOAD" >> $GITHUB_ENV
           echo ${env.JSON_PAYLOAD}
           #echo "::set-output name=changed_files::${CHANGED_FILES}"
      - name: make a post request to review bot review comments api
        run: |
          API_URL="https://pitaeva-deploy-code-review-bot.hf.space/reviewcomments" # Replace with your API endpoint
          REQUEST_BODY="{ changes: ${{ env.JSON_PAYLOAD }} }"
          echo "Request body:"
          echo "$REQUEST_BODY"
          RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{ "changes": $JSON_PAYLOAD }' "${API_URL}")
          echo "API Response:"
          echo "$RESPONSE"
          
