name: GitHub Actions on Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  call-review-bot-api:
    runs-on: ubuntu-latest
    steps:
      - name: make a post request to review bot api
        run: |
          #API_URL="curl https://pitaeva-deploy-code-review-bot.hf.space/health" # Replace with your API endpoint
          #RESPONSE=$(curl -s "$API_URL")
          echo "API Response:"
          #echo "$RESPONSE"
